import Link from "next/link";
import { MatchTable } from "@/components/match-table";
import { Shell } from "@/components/shell";
import { StatCard } from "@/components/stat-card";
import { getMarkets, getMatches } from "@/lib/api";

export default async function Dashboard() {
  const [matches, markets] = await Promise.all([getMatches(), getMarkets()]);
  return <Shell><header className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Terminal privado de análisis</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Resumen</h1><p className="mt-2 text-sm text-slate-400">Un centro de análisis para revisar contexto, precio y valor estimado.</p></div><span className="rounded border border-amber-500/30 bg-amber-400/10 px-3 py-2 text-xs font-medium text-amber-300">MVP · DATOS MOCK</span></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Partidos" value={String(matches.length)} detail="partidos monitorizados" /><StatCard label="Mercados" value={String(markets.length)} detail="cuotas disponibles" /><StatCard label="Cuotas registradas" value={String(markets.length)} detail="instantáneas mock" /><StatCard label="Muestras históricas" value={String(matches.length * 40)} detail="observaciones sintéticas" /><StatCard label="Ventajas potenciales" value="2" detail="estimaciones > 3 pp" /></section><section className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_0.9fr]"><div><div className="mb-3 flex items-center justify-between"><div><p className="eyebrow">Monitor de partidos</p><h2 className="mt-1 text-lg font-medium text-white">Próximos partidos</h2></div><Link className="text-sm text-cyan-400 hover:text-cyan-200" href="/matches">Abrir explorador →</Link></div>{matches.length ? <MatchTable matches={matches} /> : <div className="panel p-6 text-sm text-slate-500">No hay partidos disponibles.</div>}</div><div className="space-y-6"><div className="panel p-5"><p className="eyebrow">Actividad reciente</p><div className="mt-4 space-y-4 text-sm"><p><span className="mr-2 text-cyan-400">09:42</span>3 instantáneas mock normalizadas</p><p><span className="mr-2 text-cyan-400">09:18</span>Estadísticas L5 calculadas</p><p><span className="mr-2 text-cyan-400">08:55</span>Motor de combinadas disponible</p></div></div><div className="panel border-cyan-500/20 p-5"><p className="eyebrow">Metodología</p><p className="mt-2 text-sm leading-6 text-slate-400">Todos los valores de este entorno son demostrativos. Ventaja, EV y probabilidades no son recomendaciones ni garantías.</p></div></div></section></Shell>;
}
