import { DashboardWorkspace } from "@/components/dashboard-workspace";
import { Shell } from "@/components/shell";
import { SportSwitch } from "@/components/sport-switch";
import { getMarkets, getMatches } from "@/lib/api";
import { getActiveSport, sportLabels } from "@/lib/sport";

export default async function Dashboard() { const sport = await getActiveSport(); const [matches, markets] = await Promise.all([getMatches(sport), getMarkets(sport)]); return <Shell><header className="mx-auto mb-8 max-w-6xl text-center"><SportSwitch prominent /><p className="eyebrow mt-7">Centro de análisis</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Análisis de {sportLabels[sport].toLowerCase()}</h1><p className="mt-2 text-sm text-slate-400">Análisis de partidos y mercados basado en datos mock.</p></header><main className="mx-auto max-w-6xl"><DashboardWorkspace sport={sport} matches={matches} markets={markets} /><section className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="panel p-5"><p className="eyebrow">Metodología</p><h2 className="mt-1 text-lg font-medium text-white">Cómo interpretamos el valor</h2><div className="mt-4 grid gap-4 text-sm text-slate-400 sm:grid-cols-2"><Info title="Probabilidad implícita" text="La probabilidad aproximada que refleja la cuota actual del mercado." /><Info title="Probabilidad histórica" text="Una estimación basada en el comportamiento histórico relevante disponible." /><Info title="Ventaja estimada" text="La diferencia entre nuestra probabilidad estimada y la probabilidad implícita." /><Info title="Valor esperado (EV)" text="Una estimación matemática que considera probabilidad y cuota." /></div></div>{sport === "tennis" && <TennisRanking />}</section></main></Shell>; }
function Info({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border border-slate-800/80 bg-slate-950/25 p-3"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-cyan-400" /><p className="font-medium text-slate-200">{title}</p></div><p className="mt-2 leading-5 text-slate-500">{text}</p></div>; }
function TennisRanking() { const players = [["Jannik Sinner", "11.480", "↑"], ["Carlos Alcaraz", "9.250", "↑"], ["Alexander Zverev", "7.890", "—"], ["Novak Djokovic", "7.410", "↓"], ["Daniil Medvedev", "6.980", "↑"]]; return <div className="panel p-5"><p className="eyebrow">Tenis</p><h2 className="mt-1 text-lg font-medium text-white">🏆 Ranking actual</h2><div className="mt-4 space-y-3">{players.map(([name, points, trend], index) => <div key={name} className="flex items-center justify-between border-b border-slate-800 pb-3 text-sm last:border-0"><span><span className="mr-3 text-slate-500">#{index + 1}</span><span className="text-slate-200">{name}</span></span><span className="text-right text-slate-400">{points} pts <span className={trend === "↓" ? "text-rose-300" : "text-emerald-300"}>{trend}</span></span></div>)}</div><span className="mt-4 inline-flex text-sm text-slate-500">Ver ranking completo → (próximamente)</span></div>; }
