import type { ParlayHistoryEntry } from "./types";

export const parlayHistoryMock: ParlayHistoryEntry[] = [
  { id: "018", date: "2026-08-18", title: "Liga Ibérica + Premier", sport: "football", status: "lost", picks: [{ event: "Atlético Norte", market: "Total de goles", selection: "Más de 1.5", odds: 1.55, status: "won" }, { event: "Real Montaña", market: "Resultado", selection: "Local", odds: 1.42, status: "won" }, { event: "West Harbour", market: "Total de goles", selection: "Más de 2.5", odds: 1.65, status: "lost" }, { event: "Kingsbridge", market: "Ambos equipos marcan", selection: "Sí", odds: 1.7, status: "won" }] },
  { id: "017", date: "2026-08-17", title: "Open de Datos", sport: "tennis", status: "won", picks: [{ event: "Lucía Soler", market: "Ganador del partido", selection: "Lucía Soler", odds: 1.7, status: "won" }, { event: "Nora Campos", market: "Total de juegos", selection: "Más de 21.5", odds: 1.8, status: "won" }, { event: "Paula Marín", market: "Hándicap de juegos", selection: "-2.5", odds: 1.9, status: "won" }] },
  { id: "016", date: "2026-08-15", title: "Combinada del día", sport: "football", status: "won", picks: [{ event: "Costa Azul", market: "Resultado", selection: "Local", odds: 1.8, status: "won" }, { event: "Deportivo Río", market: "Total de goles", selection: "Menos de 3.5", odds: 1.5, status: "won" }] },
  { id: "015", date: "2026-08-10", title: "Circuito Ibérico", sport: "tennis", status: "pending", picks: [{ event: "Marta Vidal", market: "Ganador del partido", selection: "Marta Vidal", odds: 2.1, status: "pending" }, { event: "Elena Costa", market: "Total de juegos", selection: "Más de 22.5", odds: 1.87, status: "pending" }] },
  { id: "014", date: "2026-07-28", title: "Selecciones de julio", sport: "football", status: "lost", picks: [{ event: "Puerto Real", market: "Resultado", selection: "Local", odds: 1.9, status: "lost" }, { event: "River Town", market: "Ambos equipos marcan", selection: "Sí", odds: 1.75, status: "won" }] },
];
