import { notFound } from "next/navigation";
import { Shell } from "@/components/shell";
import { TeamLogo } from "@/components/team-logo";
import { getMatch, getTeamAnalysis } from "@/lib/api";
import { getActiveSport, sportLabels } from "@/lib/sport";

export default async function MatchPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const sport = await getActiveSport(); const match = await getMatch(id, sport); if (!match) notFound();
  const [home, away] = sport === "football" ? await Promise.all([getTeamAnalysis(match.home_team_id, match.competition_id, match.season), getTeamAnalysis(match.away_team_id, match.competition_id, match.season)]) : [null, null];
  return <Shell><header className="panel p-6"><div className="eyebrow">{sportLabels[sport]} · {match.competition}</div><div className="mt-7 grid grid-cols-[1fr_auto_1fr] items-center gap-4 text-center"><Participant name={match.home_team} logo={match.home_logo} side="Local" /><strong className="text-3xl text-white">{match.score ?? new Date(match.starts_at).toLocaleTimeString("es", { hour: "2-digit", minute: "2-digit" })}</strong><Participant name={match.away_team} logo={match.away_logo} side="Visitante" /></div><div className="mt-5 flex justify-center gap-5 text-xs text-slate-500"><span>{match.venue}</span><span>Fuente: {match.source}</span></div></header>{home && away && <Analysis home={home} away={away} homeName={match.home_team} awayName={match.away_team} />}<section className="panel mt-7 p-5"><p className="eyebrow">Mercados disponibles</p><h2 className="mt-1 text-xl font-semibold text-white">Lectura de cuotas</h2>{match.markets.length ? match.markets.map(q => <div key={q.id} className="flex justify-between border-b border-slate-800 py-4 text-sm"><span>{q.market} · {q.selection}</span><b className="text-cyan-200">{q.odds.toFixed(2)}</b></div>) : <p className="mt-4 text-sm text-slate-500">No hay mercados disponibles.</p>}</section></Shell>;
}
function Participant({ name, logo, side }: { name: string; logo?: string | null; side: string }) { return <div><TeamLogo name={name} src={logo} size={64} /><p className="mt-3 font-semibold text-slate-100">{name}</p><p className="eyebrow mt-1">{side}</p></div>; }
function Analysis({ home, away, homeName, awayName }: { home: NonNullable<Awaited<ReturnType<typeof getTeamAnalysis>>>; away: NonNullable<Awaited<ReturnType<typeof getTeamAnalysis>>>; homeName: string; awayName: string }) { const h = home.statistics.general; const a = away.statistics.general; const hf = home.form.windows.L5; const af = away.form.windows.L5; const rows: [string, number | null | undefined, number | null | undefined][] = [["Victorias", h.wins, a.wins], ["Empates", h.draws, a.draws], ["Derrotas", h.losses, a.losses], ["Goles a favor", h.goals_for, a.goals_for], ["Goles en contra", h.goals_against, a.goals_against], ["Promedio GF", h.goals_for_avg, a.goals_for_avg], ["Promedio GC", h.goals_against_avg, a.goals_against_avg]]; return <section className="panel mt-7 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow text-cyan-200">Datos reales · {home.statistics.source}</p><h2 className="mt-1 text-xl font-semibold text-white">Estadísticas y forma reciente</h2></div><span className="text-xs text-slate-500">Temporada {home.statistics.season}</span></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] gap-x-4 text-sm"><strong className="text-right text-slate-100">{homeName}</strong><span /><strong className="text-slate-100">{awayName}</strong>{rows.map(([label, hv, av]) => <div className="contents" key={label}><span className="text-right text-slate-300">{hv ?? "—"}</span><span className="text-center text-[10px] uppercase tracking-wider text-slate-500">{label}</span><span className="text-slate-300">{av ?? "—"}</span></div>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2"><Form title={`${homeName} · L5`} data={hf} /><Form title={`${awayName} · L5`} data={af} /></div></section>; }
function Form({ title, data }: { title: string; data: { sample_size: number; wins: number; draws: number; losses: number; points_percentage: number; matches: Array<{ result: string; opponent: string }> } }) { return <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex justify-between"><h3 className="text-sm text-white">{title}</h3><span className="text-xs text-slate-500">{data.sample_size} disponibles</span></div><div className="mt-3 flex gap-2">{data.matches.map((item, index) => <span key={`${item.opponent}-${index}`} title={`vs ${item.opponent}`} className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${item.result === "W" ? "bg-emerald-400/20 text-emerald-300" : item.result === "D" ? "bg-amber-400/20 text-amber-300" : "bg-rose-400/20 text-rose-300"}`}>{item.result}</span>)}</div><p className="mt-3 text-xs text-slate-500">{data.wins}V · {data.draws}E · {data.losses}D · {Math.round(data.points_percentage * 100)}% puntos</p></div>; }
