"use client";
import { useMemo, useState } from "react";
import type { MarketQuote } from "@/lib/types";

export function BuilderPanel({ markets }: { markets: MarketQuote[] }) {
  const [selected, setSelected] = useState<string[]>(markets.slice(0, 2).map((item) => item.id));
  const [targetOdds, setTargetOdds] = useState(3.5);
  const [minEdge, setMinEdge] = useState(0.03);
  const picked = useMemo(() => markets.filter((item) => selected.includes(item.id)), [markets, selected]);
  const combinedOdds = picked.reduce((total, item) => total * item.odds, 1);
  const modelProbability = picked.length ? Math.pow(0.58, picked.length) : 0;
  const impliedProbability = combinedOdds ? 1 / combinedOdds : 0;
  const edge = modelProbability - impliedProbability;
  const ev = modelProbability * combinedOdds - 1;
  const qualifies = picked.length > 0 && combinedOdds >= targetOdds && edge >= minEdge;
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  return <div className="grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><div className="panel p-5"><p className="eyebrow">Selecciones disponibles</p><div className="mt-4 space-y-2">{markets.map((item) => <label key={item.id} className="flex cursor-pointer items-center justify-between rounded border border-slate-800 bg-slate-950/40 p-3 text-sm hover:border-cyan-700"><span className="flex items-center gap-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} /> <span className="text-slate-200">{item.selection} <span className="text-slate-500">· {item.market}</span></span></span><span className="font-semibold text-cyan-300">{item.odds.toFixed(2)}</span></label>)}</div>{!markets.length && <p className="mt-4 text-sm text-slate-500">No hay cuotas mock disponibles.</p>}</div><div className="panel p-5"><p className="eyebrow">Parámetros de la candidata</p><label className="mt-4 block text-sm text-slate-400">Cuota objetivo<input aria-label="Cuota objetivo" className="mt-2 w-full rounded border border-slate-700 bg-slate-950 p-2 text-white" type="number" min="1" step="0.1" value={targetOdds} onChange={(event) => setTargetOdds(Number(event.target.value))} /></label><label className="mt-4 block text-sm text-slate-400">Ventaja mínima<input aria-label="Ventaja mínima" className="mt-2 w-full rounded border border-slate-700 bg-slate-950 p-2 text-white" type="number" min="0" max="1" step="0.01" value={minEdge} onChange={(event) => setMinEdge(Number(event.target.value))} /></label><div className="mt-5 space-y-2 border-t border-slate-800 pt-4 text-sm"><p className="flex justify-between"><span className="text-slate-500">Cuota combinada</span><span className="text-white">{combinedOdds.toFixed(2)}</span></p><p className="flex justify-between"><span className="text-slate-500">Prob. estimada mock</span><span className="text-white">{(modelProbability * 100).toFixed(1)}%</span></p><p className="flex justify-between"><span className="text-slate-500">Ventaja (Edge)</span><span className={edge >= 0 ? "text-emerald-300" : "text-rose-300"}>{(edge * 100).toFixed(1)} pp</span></p><p className="flex justify-between"><span className="text-slate-500">Valor esperado (EV)</span><span className={ev >= 0 ? "text-emerald-300" : "text-rose-300"}>{(ev * 100).toFixed(1)}%</span></p></div><div className={`mt-5 rounded border p-3 text-sm ${qualifies ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-200" : "border-slate-700 bg-slate-950/60 text-slate-400"}`}>{qualifies ? "Combinada candidata válida para revisión." : "Ajusta las selecciones o los parámetros para alcanzar los umbrales."}</div><p className="mt-4 text-xs leading-5 text-slate-500">Estimación sintética para validar el flujo del MVP; no es una recomendación ni una garantía.</p></div></div>;
}
