"use client";
import Link from "next/link";
import type { Match, Sport } from "@/lib/types";
import { groupMatchesByCompetition, groupSecondary } from "@/lib/competition-groups";
import { TeamLogo } from "@/components/team-logo";

export function CompetitionGroups({ matches, sport }: { matches: Match[]; sport: Sport }) {
  const groups = groupMatchesByCompetition(matches);
  return <div className="space-y-3">{groups.map((group) => <details key={group.key} open className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/45"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-5 py-4 hover:bg-slate-800/40"><span><strong className="text-base text-slate-100">{group.label}</strong><span className="ml-3 text-xs text-slate-500">{group.key === "other" ? `${new Set(group.matches.map((match) => match.competition)).size} competiciones · ` : ""}{group.matches.length} partidos</span></span><span className="text-cyan-300">⌄</span></summary>{group.key === "other" ? <div className="space-y-2 border-t border-slate-800 p-3">{groupSecondary(group.matches).map(([label, secondary]) => <details key={label} open className="rounded-xl border border-slate-800/80 bg-slate-950/30"><summary className="flex cursor-pointer list-none justify-between px-4 py-3 text-sm font-medium text-slate-300"><span>{label}</span><span className="text-xs text-slate-500">{secondary.length}</span></summary><div className="space-y-2 border-t border-slate-800/80 p-2">{secondary.map((match) => <FixtureRow key={match.id} match={match} sport={sport} />)}</div></details>)}</div> : <div className="space-y-2 border-t border-slate-800 p-3">{group.matches.map((match) => <FixtureRow key={match.id} match={match} sport={sport} />)}</div>}</details>)}{!groups.length && <div className="rounded-2xl border border-dashed border-slate-700 p-8 text-sm text-slate-500">No hay partidos para esta fecha.</div>}</div>;
}
function FixtureRow({ match, sport }: { match: Match; sport: Sport }) { return <Link href={`/matches/${match.id}`} className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 rounded-xl border border-slate-800/70 bg-slate-950/30 px-4 py-3 text-center transition hover:border-cyan-400/30"><span className="flex items-center justify-end gap-2 text-sm text-slate-200"><span>{match.home_team}</span><TeamLogo name={match.home_team} src={sport === "football" ? match.home_logo : undefined} size={28} /></span><span className="text-xs font-semibold text-slate-500">{match.score ?? new Date(match.starts_at).toLocaleTimeString("es", { hour: "2-digit", minute: "2-digit" })}</span><span className="flex items-center gap-2 text-left text-sm text-slate-200"><TeamLogo name={match.away_team} src={sport === "football" ? match.away_logo : undefined} size={28} /><span>{match.away_team}</span></span></Link>; }
