"use client";
import { useMemo, useState } from "react";
import type { Match, Sport } from "@/lib/types";
import { CompetitionGroups } from "@/components/competition-groups";

export function MatchExplorer({ matches, sport = "football" }: { matches: Match[]; sport?: Sport }) {
  const [team, setTeam] = useState(""); const [competition, setCompetition] = useState(""); const [status, setStatus] = useState(""); const [date, setDate] = useState("");
  const filtered = useMemo(() => matches.filter((match) => { const text = `${match.home_team} ${match.away_team}`.toLowerCase(); return (!team || text.includes(team.toLowerCase())) && (!competition || match.competition === competition) && (!status || match.status === status) && (!date || match.starts_at.slice(0, 10) === date); }), [matches, team, competition, status, date]);
  const competitions = [...new Set(matches.map((match) => match.competition))];
  return <div><div className="rounded-2xl border border-slate-800 bg-[#0b1321] p-4"><div className="grid gap-3 md:grid-cols-[1.2fr_1fr_1fr_auto]"><input aria-label="Buscar equipo" value={team} onChange={(event) => setTeam(event.target.value)} placeholder="Buscar equipo o jugador" className="rounded-xl border border-slate-700 bg-slate-950/70 px-4 py-3 text-sm placeholder:text-slate-600" /><select aria-label="Competición" value={competition} onChange={(event) => setCompetition(event.target.value)} className="rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-3 text-sm"><option value="">Competición</option>{competitions.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Estado" value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-3 text-sm"><option value="">Estado</option><option value="scheduled">Programados</option><option value="finished">Finalizados</option></select><input aria-label="Fecha" type="date" value={date} onChange={(event) => setDate(event.target.value)} className="rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-3 text-sm" /></div></div><div className="my-6 flex items-center justify-between"><p className="text-sm text-slate-400"><strong className="text-white">{filtered.length}</strong> eventos encontrados</p><span className="text-[10px] uppercase tracking-[.16em] text-slate-600">Match center</span></div><CompetitionGroups matches={filtered} sport={sport} /></div>;
}
