"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
const groups = [
  { label: "Resumen", items: [["Resumen", "/dashboard"]] },
  { label: "Análisis", items: [["Partidos", "/matches"], ["Mercados", "/markets"], ["Historial", "/history"]] },
  { label: "Valor", items: [["Analizador de combinadas", "/parlay"], ["Constructor de combinadas", "/parlay/builder"]] },
  { label: "Datos", items: [["Datos", "#"]] },
  { label: "Sistema", items: [["Configuración", "#"]] },
];
export function Shell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); return <div className="min-h-screen lg:grid lg:grid-cols-[238px_1fr]"><aside className="border-b border-slate-800/80 bg-[#09111e]/95 px-5 py-6 lg:border-b-0 lg:border-r"><Link href="/dashboard" className="mb-9 block text-xl font-bold tracking-tight text-white">PARACO<span className="text-cyan-400">BET</span><span className="ml-2 align-middle text-[9px] font-medium uppercase tracking-[0.2em] text-slate-500">Analytics</span></Link><nav className="max-h-[calc(100vh-180px)] space-y-6 overflow-y-auto pr-1">{groups.map((group) => <div key={group.label}><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">{group.label}</p>{group.items.map(([label, href]) => href === "#" ? <span key={label} className="mb-1 flex items-center justify-between rounded-lg px-3 py-2 text-sm text-slate-600" title="Disponible próximamente">{label}<span className="text-[9px] uppercase tracking-wider">Próximamente</span></span> : <Link key={label} href={href} className={`mb-1 block rounded-lg border px-3 py-2.5 text-sm transition ${pathname === href || (href !== "/dashboard" && pathname.startsWith(`${href}/`)) ? "border-cyan-400/25 bg-cyan-400/10 font-medium text-cyan-200 shadow-[inset_3px_0_0_#58b8ff]" : "border-transparent text-slate-300 hover:border-slate-700/80 hover:bg-slate-800/70 hover:text-white"}`}>{label}</Link>)}</div>)}</nav><div className="mt-8 border-t border-slate-800/80 pt-4 text-xs text-slate-500"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-400 shadow-[0_0_10px_rgba(242,198,109,.5)]" />Datos sintéticos · Mock</div></aside><main className="min-w-0 p-5 sm:p-8">{children}</main></div>; }
